import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';
import { appConfig } from '../app-config';
import { Header } from './_header/header';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import { getCurrentUser } from '@/lib/session';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'dark')}>
        <NextTopLoader color="#dbb73f" />
        <div className="flex flex-col w-full">
          {appConfig.mode === 'live' && <Header />}
          <div>
            {children}
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
